// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// The installed @prisma/config (7.9.1) datasource only supports `url` (+ shadowDatabaseUrl),
// no `directUrl` — that field was dropped after prisma 7.6. The CLI (migrate/introspect)
// needs a non-pooled connection, so it uses DIRECT_URL here. The running app uses the pooled
// DATABASE_URL separately via the driver adapter in src/lib/prisma.ts.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
